name = "H2hpack"
uuid = "03a3583f-3b84-4ec3-931d-7334ff455684"
license = "MIT"
authors = ["Gerasimos Panou <gerasimos.panou]@gmail.com>"]
description = "HPACK (HTTP/2 Header Compression) implementation in Julia."
version = "0.2.3"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Julia = "1.11"
Documenter = "1.13.0"
