name = "HPACK"
uuid = "03a3583f-3b84-4ec3-931d-7334ff455684"
authors = ["Gerasimos Panou <gerasimos.panou]@gmail.com>"]
version = "0.1.0"
description = "HPACK (HTTP/2 Header Compression) implementation in Julia."
license = "MIT"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
